name: Pipeline Backend
on:
 push:
  branches: [ master ]
 pull_request:
  branches: [ master ]
 workflow_dispatch:
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pytest flask typing_extensions
    - name: Pylint
      run: pylint $(find . -name "*.py" | xargs)
    - name: Pytest
      run: pylint $(find . -name "test_*.py" | xargs)
